[comment]==Pokéball==[/comment]
		[div=width: 50px; height: 50px; background: #fff; border: 2px solid #000; border-radius: 50%;
		overflow: hidden; box-shadow: inset -10px 10px 0 10px #ccc; box-sizing: box-border; transform: rotate(-25deg);]
			[comment]==Red Top==[/comment]
			[div=background: #f93318; width: 100%; height: 100%; position: absolute; top: -50%;box-sizing: box-border;][/div]
			[comment]==White Bottom==[/comment]
			[div=top: calc(50% - 10px); width: 100%; height: 100px; background: #000; box-sizing: box-border;][/div]
			[comment]==Pokeball Button==[/comment]
			[div=position: absolute; top: calc(50% - 5px); left: calc(50% - 5px); width: 7px; height: 7px; background: #7f8c8d; border: 2px solid #fff; border-radius: 50%; z-index: 10;box-shadow: 0 0 0 2px black; box-sizing: box-border;][/div]
		[/div]